import type { LayerGroup } from '../types'

const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0]

export const EARTH_LAYERS: LayerGroup[] = [
  {
    id: 'commercial_hr',
    label: '── COMMERCIAL HIGH-RES',
    layers: [
      {
        id: 'esri_world',
        name: 'ESRI World Imagery',
        url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
        attribution: '© Esri, Maxar, Earthstar Geographics',
        resolution: '~30–60cm (urban)',
        updateFrequency: 'Periodically updated',
        source: 'Esri / Maxar / Nearmap',
        classification: 'FREE',
        maxZoom: 19,
      },
      {
        id: 'esri_clarity',
        name: 'ESRI Clarity (Beta)',
        url: 'https://clarity.maptiles.arcgis.com/arcgis/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
        attribution: '© Esri',
        resolution: '~30cm (select regions)',
        updateFrequency: 'Periodic',
        source: 'Esri Clarity',
        classification: 'FREE',
        maxZoom: 19,
      },
    ],
  },
  {
    id: 'nasa_realtime',
    label: '── NASA NEAR REAL-TIME',
    layers: [
      {
        id: 'gibs_viirs_today',
        name: 'VIIRS SNPP True Color (Today)',
        url: `https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/VIIRS_SNPP_CorrectedReflectance_TrueColor/default/${yesterday}/GoogleMapsCompatible_Level9/{z}/{y}/{x}.jpg`,
        attribution: 'NASA GIBS / VIIRS',
        resolution: '375m',
        updateFrequency: 'Near real-time (<3h)',
        source: 'NASA EOSDIS / LANCE',
        classification: 'FREE',
        maxZoom: 9,
      },
      {
        id: 'gibs_modis_terra',
        name: 'MODIS Terra True Color',
        url: `https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Terra_CorrectedReflectance_TrueColor/default/${yesterday}/GoogleMapsCompatible_Level9/{z}/{y}/{x}.jpg`,
        attribution: 'NASA GIBS / MODIS Terra',
        resolution: '250m',
        updateFrequency: 'Daily',
        source: 'NASA EOSDIS',
        classification: 'FREE',
        maxZoom: 9,
      },
      {
        id: 'gibs_modis_aqua',
        name: 'MODIS Aqua True Color',
        url: `https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/MODIS_Aqua_CorrectedReflectance_TrueColor/default/${yesterday}/GoogleMapsCompatible_Level9/{z}/{y}/{x}.jpg`,
        attribution: 'NASA GIBS / MODIS Aqua',
        resolution: '250m',
        updateFrequency: 'Daily',
        source: 'NASA EOSDIS',
        classification: 'FREE',
        maxZoom: 9,
      },
    ],
  },
  {
    id: 'nasa_static',
    label: '── NASA SATELLITE',
    layers: [
      {
        id: 'gibs_blue_marble',
        name: 'Blue Marble Next Gen',
        url: 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/BlueMarble_NextGeneration/default/2004-08-01/GoogleMapsCompatible_Level8/{z}/{y}/{x}.jpg',
        attribution: 'NASA GIBS / Blue Marble',
        resolution: '500m',
        updateFrequency: 'Monthly composite',
        source: 'NASA / MODIS',
        classification: 'FREE',
        maxZoom: 8,
      },
      {
        id: 'gibs_landsat',
        name: 'Landsat 8/9 OLI (Global)',
        url: 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/Landsat_WELD_CorrectedReflectance_TrueColor_Global_Annual/default/2019-01-01/GoogleMapsCompatible_Level12/{z}/{y}/{x}.jpg',
        attribution: 'NASA GIBS / USGS Landsat',
        resolution: '30m',
        updateFrequency: 'Annual mosaic',
        source: 'NASA / USGS Landsat',
        classification: 'FREE',
        maxZoom: 12,
      },
      {
        id: 'gibs_nighttime',
        name: 'Earth at Night (VIIRS)',
        url: 'https://gibs.earthdata.nasa.gov/wmts/epsg3857/best/VIIRS_SNPP_DayNightBand_ENCC/default/2021-06-15/GoogleMapsCompatible_Level8/{z}/{y}/{x}.png',
        attribution: 'NASA GIBS / VIIRS DNB',
        resolution: '500m',
        updateFrequency: 'Composite',
        source: 'NASA / NOAA VIIRS',
        classification: 'FREE',
        maxZoom: 8,
      },
    ],
  },
  {
    id: 'gov_aerial',
    label: '── GOVERNMENT AERIAL',
    layers: [
      {
        id: 'usgs_naip',
        name: 'USDA NAIP Aerial (USA 0.6m)',
        url: 'https://gis.apfo.usda.gov/arcgis/rest/services/NAIP/USDA_CONUS_PRIME/ImageServer/tile/{z}/{y}/{x}',
        attribution: 'USDA FSA NAIP',
        resolution: '0.6m (60cm)',
        updateFrequency: '1-3 years',
        source: 'USDA FSA NAIP',
        classification: 'FREE',
        maxZoom: 18,
      },
      {
        id: 'usgs_imagery_topo',
        name: 'USGS Imagery Topo (USA)',
        url: 'https://basemap.nationalmap.gov/arcgis/rest/services/USGSImageryTopo/MapServer/tile/{z}/{y}/{x}',
        attribution: 'USGS The National Map',
        resolution: '1m',
        updateFrequency: 'Periodic',
        source: 'USGS National Map',
        classification: 'FREE',
        maxZoom: 16,
      },
    ],
  },
  {
    id: 'planet_nicfi',
    label: '── PLANET LABS (NICFI)',
    layers: [
      {
        id: 'planet_nicfi_analytic',
        name: 'Planet NICFI Tropics (4.77m)',
        url: 'https://tiles.planet.com/basemaps/v1/planet-tiles/planet_medres_normalized_analytic_2023-12_mosaic/gmap/{z}/{x}/{y}.png?api_key={PLANET_API_KEY}',
        attribution: '© Planet Labs PBC / NICFI',
        resolution: '4.77m',
        updateFrequency: 'Monthly mosaics',
        source: 'Planet SuperDove / NICFI',
        classification: 'RESTRICTED',
        maxZoom: 15,
        requiresKey: true,
        keyName: 'planetApiKey',
        signupUrl: 'https://www.planet.com/nicfi/',
      },
      {
        id: 'planet_nicfi_visual',
        name: 'Planet NICFI Tropics Visual (4.77m)',
        url: 'https://tiles.planet.com/basemaps/v1/planet-tiles/planet_medres_visual_2023-12_mosaic/gmap/{z}/{x}/{y}.png?api_key={PLANET_API_KEY}',
        attribution: '© Planet Labs PBC / NICFI',
        resolution: '4.77m',
        updateFrequency: 'Monthly mosaics',
        source: 'Planet SuperDove / NICFI',
        classification: 'RESTRICTED',
        maxZoom: 15,
        requiresKey: true,
        keyName: 'planetApiKey',
        signupUrl: 'https://www.planet.com/nicfi/',
      },
    ],
  },
  {
    id: 'basemaps',
    label: '── BASEMAPS / REFERENCE',
    layers: [
      {
        id: 'osm',
        name: 'OpenStreetMap',
        url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
        attribution: '© OpenStreetMap contributors',
        resolution: 'Vector',
        updateFrequency: 'Continuous',
        source: 'OpenStreetMap',
        classification: 'OPEN',
        maxZoom: 19,
      },
      {
        id: 'esri_topo',
        name: 'ESRI World Topo',
        url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}',
        attribution: '© Esri',
        resolution: 'Vector + Raster',
        updateFrequency: 'Periodic',
        source: 'Esri',
        classification: 'FREE',
        maxZoom: 18,
      },
    ],
  },
]

const USGS_WMS = 'https://planetarymaps.usgs.gov/cgi-bin/mapserv'

export const MOON_LAYERS: LayerGroup[] = [
  {
    id: 'lroc',
    label: '── LROC / LRO',
    layers: [
      {
        id: 'moon_wac_mosaic',
        name: 'LROC WAC Global Mosaic (100m)',
        url: `${USGS_WMS}?map=/maps/earth/moon_simp_cyl.map`,
        wmsLayers: 'LROC_WAC',
        attribution: 'USGS Astrogeology / NASA LRO LROC',
        resolution: '100m',
        updateFrequency: 'Mission archive',
        source: 'LRO LROC WAC',
        classification: 'FREE',
        type: 'wms',
        format: 'image/jpeg',
        minZoom: 0,
        maxZoom: 10,
      },
      {
        id: 'moon_lola_dem',
        name: 'LOLA Elevation Color',
        url: `${USGS_WMS}?map=/maps/earth/moon_simp_cyl.map`,
        wmsLayers: 'LOLA_color',
        attribution: 'USGS Astrogeology / NASA LRO LOLA',
        resolution: '256m (elevation)',
        updateFrequency: 'Mission archive',
        source: 'LRO LOLA',
        classification: 'FREE',
        type: 'wms',
        format: 'image/jpeg',
        minZoom: 0,
        maxZoom: 8,
      },
      {
        id: 'moon_kaguya',
        name: 'Kaguya TC (JAXA, 10m)',
        url: `${USGS_WMS}?map=/maps/earth/moon_simp_cyl.map`,
        wmsLayers: 'KaguyaTC_Ortho',
        attribution: 'USGS Astrogeology / JAXA SELENE Kaguya',
        resolution: '10m',
        updateFrequency: 'Mission archive',
        source: 'JAXA Kaguya TC',
        classification: 'FREE',
        type: 'wms',
        format: 'image/jpeg',
        minZoom: 0,
        maxZoom: 10,
      },
    ],
  },
]

export const MARS_LAYERS: LayerGroup[] = [
  {
    id: 'mars_color',
    label: '── COLOR MOSAICS',
    layers: [
      {
        id: 'mars_viking_color',
        name: 'Viking MDIM 2.1 Color (232m)',
        url: `${USGS_WMS}?map=/maps/mars/mars_simp_cyl.map`,
        wmsLayers: 'MDIM21_color',
        attribution: 'USGS Astrogeology / NASA Viking',
        resolution: '232m',
        updateFrequency: 'Mission archive',
        source: 'NASA Viking Orbiter',
        classification: 'FREE',
        type: 'wms',
        format: 'image/jpeg',
        minZoom: 0,
        maxZoom: 9,
      },
      {
        id: 'mars_themis',
        name: 'THEMIS Daytime IR (100m)',
        url: `${USGS_WMS}?map=/maps/mars/mars_simp_cyl.map`,
        wmsLayers: 'THEMIS',
        attribution: 'USGS Astrogeology / ASU THEMIS',
        resolution: '100m',
        updateFrequency: 'Mission archive',
        source: 'MO THEMIS',
        classification: 'FREE',
        type: 'wms',
        format: 'image/jpeg',
        minZoom: 0,
        maxZoom: 9,
      },
    ],
  },
  {
    id: 'mars_elevation',
    label: '── ELEVATION',
    layers: [
      {
        id: 'mars_mola',
        name: 'MOLA Color Elevation',
        url: `${USGS_WMS}?map=/maps/mars/mars_simp_cyl.map`,
        wmsLayers: 'MOLA_color',
        attribution: 'USGS Astrogeology / NASA MGS MOLA',
        resolution: '463m (elevation)',
        updateFrequency: 'Mission archive',
        source: 'MGS MOLA',
        classification: 'FREE',
        type: 'wms',
        format: 'image/jpeg',
        minZoom: 0,
        maxZoom: 8,
      },
    ],
  },
]

export const PLANET_CONFIGS = [
  {
    id: 'mercury',
    name: 'MERCURY',
    distance: '0.39 AU',
    layers: [
      {
        id: 'mercury_messenger',
        name: 'MESSENGER Global (166m)',
        url: `${USGS_WMS}?map=/maps/mercury/mercury_simp_cyl.map`,
        wmsLayers: 'MESSENGER',
        attribution: 'USGS Astrogeology / NASA MESSENGER',
        resolution: '166m',
        updateFrequency: 'Mission archive',
        source: 'MESSENGER MDIS',
        classification: 'FREE' as const,
        type: 'wms' as const,
        format: 'image/jpeg',
        minZoom: 0,
        maxZoom: 8,
      },
      {
        id: 'mercury_messenger_color',
        name: 'MESSENGER Color Mosaic',
        url: `${USGS_WMS}?map=/maps/mercury/mercury_simp_cyl.map`,
        wmsLayers: 'MESSENGER_Color',
        attribution: 'USGS Astrogeology / NASA MESSENGER',
        resolution: '1km (color)',
        updateFrequency: 'Mission archive',
        source: 'MESSENGER MDIS',
        classification: 'FREE' as const,
        type: 'wms' as const,
        format: 'image/jpeg',
        minZoom: 0,
        maxZoom: 7,
      },
      {
        id: 'mercury_mariner',
        name: 'Mariner 10 Mosaic',
        url: `${USGS_WMS}?map=/maps/mercury/mercury_simp_cyl.map`,
        wmsLayers: 'MARINER',
        attribution: 'USGS Astrogeology / NASA Mariner 10',
        resolution: '1km (historic 1974)',
        updateFrequency: 'Mission archive',
        source: 'Mariner 10',
        classification: 'FREE' as const,
        type: 'wms' as const,
        format: 'image/jpeg',
        minZoom: 0,
        maxZoom: 6,
      },
    ],
  },
  {
    id: 'venus',
    name: 'VENUS',
    distance: '0.72 AU',
    layers: [
      {
        id: 'venus_magellan',
        name: 'Magellan SAR Radar (75m)',
        url: `${USGS_WMS}?map=/maps/venus/venus_simp_cyl.map`,
        wmsLayers: 'MAGELLAN',
        attribution: 'USGS Astrogeology / NASA Magellan',
        resolution: '75m (radar)',
        updateFrequency: 'Mission archive',
        source: 'Magellan SAR',
        classification: 'FREE' as const,
        type: 'wms' as const,
        format: 'image/jpeg',
        minZoom: 0,
        maxZoom: 8,
      },
      {
        id: 'venus_magellan_color',
        name: 'Magellan Color Altimetry',
        url: `${USGS_WMS}?map=/maps/venus/venus_simp_cyl.map`,
        wmsLayers: 'MAGELLAN_color',
        attribution: 'USGS Astrogeology / NASA Magellan',
        resolution: '1km (color elev)',
        updateFrequency: 'Mission archive',
        source: 'Magellan altimeter',
        classification: 'FREE' as const,
        type: 'wms' as const,
        format: 'image/jpeg',
        minZoom: 0,
        maxZoom: 7,
      },
      {
        id: 'venus_magellan_topo',
        name: 'Magellan Topography',
        url: `${USGS_WMS}?map=/maps/venus/venus_simp_cyl.map`,
        wmsLayers: 'MAGELLAN_topography',
        attribution: 'USGS Astrogeology / NASA Magellan',
        resolution: '1km (topo)',
        updateFrequency: 'Mission archive',
        source: 'Magellan altimeter',
        classification: 'FREE' as const,
        type: 'wms' as const,
        format: 'image/jpeg',
        minZoom: 0,
        maxZoom: 7,
      },
    ],
  },
]

export const DEEP_SPACE_SOURCES = [
  { id: 'P/DSS2/color',                       name: 'DSS2 Color (Palomar/ESO)',        telescope: 'POSS II / ESO',  resolution: '~1"'    },
  { id: 'P/PanSTARRS/DR1/color-z-zg-g',       name: 'PanSTARRS DR1 Color',             telescope: 'Pan-STARRS',    resolution: '0.25"'  },
  { id: 'P/HST/GOODS-S/b',                    name: 'Hubble GOODS-S Deep Field',       telescope: 'HST ACS',       resolution: '0.06"'  },
  { id: 'P/2MASS/color',                       name: '2MASS All-Sky (NIR)',              telescope: '2MASS',         resolution: '2"'     },
  { id: 'P/allWISE/color',                     name: 'WISE All-Sky (Infrared)',          telescope: 'WISE',          resolution: '6"'     },
  { id: 'P/GALEXGR6AIS/color',                 name: 'GALEX UV All-Sky',                telescope: 'GALEX',         resolution: '4.5"'   },
  { id: 'P/SDSS9/color',                       name: 'SDSS Visible (DR9)',               telescope: 'SDSS',          resolution: '1.4"'   },
  { id: 'P/XMM/EPIC/RGB',                      name: 'XMM-Newton X-Ray',                telescope: 'XMM-Newton',    resolution: '4"'     },
  { id: 'P/JWST/Carina',                       name: 'JWST Carina Nebula (NIRCam)',      telescope: 'JWST',          resolution: '0.031"' },
  { id: 'P/JWST/SMACS0723',                    name: 'JWST Deep Field SMACS 0723',       telescope: 'JWST',          resolution: '0.031"' },
]

export const FAMOUS_TARGETS = [
  { name: 'Andromeda Galaxy', id: 'M31', ra: 10.6833, dec: 41.2692 },
  { name: 'Orion Nebula', id: 'M42', ra: 83.8221, dec: -5.3911 },
  { name: 'Crab Nebula (Pulsar)', id: 'M1', ra: 83.6333, dec: 22.0145 },
  { name: 'Sombrero Galaxy', id: 'M104', ra: 189.9976, dec: -11.6231 },
  { name: 'Pillars of Creation', id: 'M16', ra: 274.7, dec: -13.8 },
  { name: 'Whirlpool Galaxy', id: 'M51', ra: 202.4696, dec: 47.1952 },
  { name: 'Eta Carinae Nebula', id: 'Eta Car', ra: 161.265, dec: -59.685 },
  { name: 'Stephan\'s Quintet', id: 'HCG 92', ra: 339.0146, dec: 33.9680 },
  { name: 'Cartwheel Galaxy', id: 'ESO 350-40', ra: 9.9895, dec: -33.7235 },
  { name: 'Hubble Deep Field', id: 'HDF', ra: 189.2063, dec: 62.2132 },
]
